ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  submodules: false
  skip: [badgie, regenerate-files]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-added-large-files
      - id: sort-simple-yaml
        files: .pre-commit-config.yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-format
      - id: ruff-check
        types: [file]
        types_or: [python, pyi, toml]
        args: ["--show-fixes"]
  - repo: https://github.com/CoolCat467/badgie
    rev: v0.9.6
    hooks:
      - id: badgie
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.36.3
    hooks:
      - id: typos
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.14.2
    hooks:
      - id: zizmor
  - repo: local
    hooks:
      - id: regenerate-files
        name: regenerate generated files
        language: system
        entry: python src/market_server/generate_pages.py
        pass_filenames: false
        files: ^src\/market_server\/(((htmlgen|generate_pages)\.py)|((static|templates)\/.+\.\w+))$
